// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewChapterInput struct {
	Name     string `json:"name"`
	CourseID string `json:"courseID"`
}

type NewCourseInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CategoryID  string `json:"categoryID"`
}
